# Generated by Django 5.1 on 2024-08-26 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('responses', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Response',
            new_name='rsvp',
        ),
    ]
